version: "3.8"

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=lukasz123
      - MYSQL_DATABASE=biblioteka
    ports:
      - "3307:3306"
  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/biblioteka",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "lukasz123",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql" : "true"
      }'