spring:
    datasource:
        url: jdbc:mysql://localhost:3306/biblioteka
        username: root
        password: lukasz123
    jpa:
        properties:
            hibernate:
                ddl-auto: update
        database: MYSQL
        show-sql: true
